# Generated by Django 3.0.5 on 2020-05-05 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0003_auto_20200505_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='Phone',
            new_name='phone',
        ),
    ]
